# Generated by Django 5.0.4 on 2025-09-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_phone_number_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
