# Generated by Django 5.0.4 on 2025-09-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_habit_start_date'),
    ]

    operations = [
    ]
