# Generated by Django 5.2.6 on 2025-09-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_habit_habit_type_alter_habit_icon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynote',
            name='mood',
            field=models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')]),
        ),
    ]
