# Generated by Django 5.2.6 on 2025-09-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_has_subscription_user_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Базовая'), ('premium', 'Премиум'), ('pro', 'Премиум')], default='free', max_length=20),
        ),
    ]
