# Generated by Django 5.2.6 on 2025-09-22 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('segment_0_useful', models.IntegerField(default=0)),
                ('segment_0_harmful', models.IntegerField(default=0)),
                ('segment_1_useful', models.IntegerField(default=0)),
                ('segment_1_harmful', models.IntegerField(default=0)),
                ('segment_2_useful', models.IntegerField(default=0)),
                ('segment_2_harmful', models.IntegerField(default=0)),
                ('segment_3_useful', models.IntegerField(default=0)),
                ('segment_3_harmful', models.IntegerField(default=0)),
                ('segment_4_useful', models.IntegerField(default=0)),
                ('segment_4_harmful', models.IntegerField(default=0)),
                ('segment_5_useful', models.IntegerField(default=0)),
                ('segment_5_harmful', models.IntegerField(default=0)),
                ('segment_6_useful', models.IntegerField(default=0)),
                ('segment_6_harmful', models.IntegerField(default=0)),
                ('segment_7_useful', models.IntegerField(default=0)),
                ('segment_7_harmful', models.IntegerField(default=0)),
                ('segment_8_useful', models.IntegerField(default=0)),
                ('segment_8_harmful', models.IntegerField(default=0)),
                ('segment_9_useful', models.IntegerField(default=0)),
                ('segment_9_harmful', models.IntegerField(default=0)),
                ('segment_10_useful', models.IntegerField(default=0)),
                ('segment_10_harmful', models.IntegerField(default=0)),
                ('segment_11_useful', models.IntegerField(default=0)),
                ('segment_11_harmful', models.IntegerField(default=0)),
                ('segment_12_useful', models.IntegerField(default=0)),
                ('segment_12_harmful', models.IntegerField(default=0)),
                ('segment_13_useful', models.IntegerField(default=0)),
                ('segment_13_harmful', models.IntegerField(default=0)),
                ('segment_14_useful', models.IntegerField(default=0)),
                ('segment_14_harmful', models.IntegerField(default=0)),
                ('total_useful_seconds', models.IntegerField(default=0)),
                ('total_harmful_seconds', models.IntegerField(default=0)),
                ('total_screen_time_seconds', models.IntegerField(default=0)),
                ('sessions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_timelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
