# Generated by Django 5.2.6 on 2025-09-23 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_dailytimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('useful', 'Полезное'), ('harmful', 'Вредное'), ('useless', 'Бесполезное')], default='useless', max_length=20)),
                ('icon_base64', models.TextField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('total_usage_seconds', models.IntegerField(default=0)),
                ('is_gpt_classified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
                'unique_together': {('user', 'package_name')},
            },
        ),
        migrations.CreateModel(
            name='AppUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('usage_seconds', models.IntegerField(default=0)),
                ('sessions_count', models.IntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='accounts.app')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('app', 'date')},
            },
        ),
    ]
