# Generated by Django 5.2.6 on 2025-09-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_usertestresult'),
    ]

    operations = [
    ]
