# Generated by Django 5.2.6 on 2025-09-30 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20250930_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_code_point', models.IntegerField()),
                ('icon_font_family', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_font_package', models.CharField(blank=True, max_length=100, null=True)),
                ('achievement_type', models.CharField(choices=[('daily_streak', 'Ежедневная серия'), ('ai_chat_usage', 'Использование ИИ чата'), ('app_blocking', 'Блокировка приложений'), ('low_screen_time', 'Низкое экранное время'), ('total_usage_months', 'Общее использование (месяцы)')], max_length=50)),
                ('required_value', models.IntegerField()),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at', 'achievement_type', 'required_value'],
                'unique_together': {('user', 'achievement_id')},
            },
        ),
        migrations.CreateModel(
            name='AchievementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_usage_date', models.DateField(blank=True, null=True)),
                ('consecutive_days', models.IntegerField(default=0)),
                ('ai_chat_usage_count', models.IntegerField(default=0)),
                ('app_blocking_count', models.IntegerField(default=0)),
                ('low_screen_time_days', models.IntegerField(default=0)),
                ('first_usage_date', models.DateTimeField(blank=True, null=True)),
                ('total_usage_months', models.IntegerField(default=0)),
                ('last_sync_date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
